export const INDICATORS = [
  { key: 'EMA7', label: 'EMA 7' },
  { key: 'EMA21', label: 'EMA 21' },
  { key: 'EMA50', label: 'EMA 50' },
  { key: 'EMA200', label: 'EMA 200' },
  { key: 'SMA20', label: 'SMA 20' },
  { key: 'SMA50', label: 'SMA 50' },
  { key: 'UpperBB', label: 'Upper BB' },
  { key: 'LowerBB', label: 'Lower BB' },
  { key: 'RSI', label: 'RSI' },
  { key: 'MACD', label: 'MACD' },
  { key: 'STOCH', label: 'Stochastic' },
  { key: 'ADX', label: 'ADX' },
  { key: 'CCI', label: 'CCI' },
  { key: 'ATR', label: 'ATR' },
  { key: 'ROC', label: 'ROC' },
  { key: 'WILLIAMS', label: 'Williams %R' },
  { key: 'MFI', label: 'MFI' },
  { key: 'OBV', label: 'OBV' },
  { key: 'VWAP', label: 'VWAP' },
  { key: 'PSAR', label: 'PSAR' },
]